### ISSUE TITLE
Improve .osim file visualization

### ISSUE THREAD

**Issue by itbellix** [ComputationalBiomechanicsLab/opensim-creator#130]
Hi @adamkewley, I want to suggest a (very low priority) feature that I think would be nice to have in OS Creator. I see in the video for [tutorial 4](https://youtu.be/EWcMT99_nf0?t=2807) that you show how to update the model in real-time when modifying the .osim file in an text editor. In my opinion it would be very nice if you could in some way relate the body that you are selecting/highlighting with the lines that define it and its properties. Something like : if you click to a certain Millard2021EquilibriumMuscle in the model and you have the .xml viewer open, then it jumps to the section that defines that particular muscle (and maybe highlights it too). In this way, you are sure that you are editing the right things and do not loose time searching for them in case the model is very complex.

Of course, you are free to just discard this idea if it does not make particular sense, or keep it in backlog for as long as you want!

**Comment by adamkewley** [comment]
It's a really nice idea @itbellix , and I'd love if it was cleanly possible (I'll look into whether I'm wrong here, though), but I think the issue with integrating it exactly how you say (e.g. clicking in OSC highlights something in the text editor) is that the text editor is an external application that OSC doesn't know anything about.

What I mean is that the underlying code in OSC for opening the text editor is something like:

```text
open_in_default_editor("file.osim");
```

And the underlying operating system (e.g. Windows) will have some default application that it assigns for that file type (in my case, I use sublimetext with osim files). The OS will then separately boot up that application and pass it in as an argument, something like:

```text
exec("sublimetext.exe", "file.osim");
```

But the OS *also* doesn't know what it's booting. It just knows that if it sees an `osim` file it should boot `sublimetext` with it as an application argument.

However, it might be that the external application does actually have support for jumping to a line on boot, something like `sublimetext.exe file.osim:83`, but integrating that into OpenSim Creator would require a configuration dialog somewhere where a user can set a custom application when opening an osim file. Say, a UI box that lets them specify `sublimetext.exe ${filename}:${linenumber}`.

I think it's something that needs to be fixed, UX-wise, though because, yeah, it was a bit painful to find the muscle in the osim. Maybe something as simple as letting the user copy the component's name into the clipboard or a UI element that says "yeah, it's at line 500 in the osim" might be enough, though :O - I'll keep this open until I can figure out what concrete actions/issues would lead to a better approach

**Comment by adamkewley** [comment]
Closing this because it isn't technically possible to do, given how OSes handle `open` requests.

OSC will always be able to open the `osim` file in an external application, but if people want to know where *exactly* in the XML file the edited component is then that will require either:

- Adding XML reflection into OSC, such that it annotates components with an XML location that can be presented to the user (e.g. mousing over a component shows its line number in the corresponding XML file)
- Or adding an in-OSC XML editor, where OSC has complete control over the editor's caret position, line number, etc.

Both of these are concrete things that can be done, and will be split into concrete issues that can either later be addressed or droppped, depending on scheduling etc.
