### ISSUE TITLE
List Forces (components) that can be added from Object::Registered types.

### ISSUE THREAD

**Issue by aseth1** [ComputationalBiomechanicsLab/opensim-creator#154]
**Estimate (Adam)**: 3-6h

Instead of pre-listing a subset of Forces (and Actuators) that can be added to the Model,  use the registered Object types to get a complete and up-to-date list. This will also include components loaded via plugins

**Comment by adamkewley** [comment]
This shouldn't be an "instead of", rather "in addition to".

The reason why is because the OpenSim object registry contains less information than the custom listed one. E.g. the in-UI documentation was manually copied from various comments etc. in the source code. That documentation is not available in the OpenSim object registry.

The complete solution would be to populate the various subsets (forces, etc.) with manual entries, which include the documentation strings and any fixups (e.g. renaming prototype subcomponents or setting default values to be something more usable); followed by searching through OpenSim's object registry to add anything that's missing (sans objects that maybe should be on a blacklist because they aren't easy to automatically add via a UI and require property data that's too complicated for the UI to automatically generate an input form for etc. etc.)

There is currently no plugin support, so that's a separate thing to address.

**Comment by adamkewley** [comment]
(added rough estimate of adding this w/o plugin support)

**Comment by adamkewley** [comment]
#158 for plugin loading: the reason it isn't included is because it's tricky to do *robustly* - esp. if we want a platform that's easy for less-experienced users to build against (e.g. incl documentation, build helpers, project generators).

**Comment by adamkewley** [comment]
This is now implemented on the master branch. #158  will have to be careful to ensure that loading a plugin causes a re-search for these registries, though
