### ISSUE TITLE
Fix editing a body's inertia property does not update the body's inertial behavior

### ISSUE THREAD

**Issue by jesse-gilmer** [ComputationalBiomechanicsLab/opensim-creator#597]
Hello,
Huge fan of this project, and thank you for all your hard work.
Is it possible to have an option to force a model update when inertial tensors are changed? I believe that OpenSim itself also does not update the model when these values are changed, and will only reflect changes when the model is completely closed and reloaded (and this is true of OSC as well), but... it's a little annoying to have to manually close the model/reload osim (thanks for this shortcut, by the way) to see changes reflected for this particular variable.
Thanks!
-JG

**Comment by adamkewley** [comment]
Oh, *interesting*: I wasn't aware that inertial tensors aren't correctly updated by an in-app edit 😱 

For the most part, OSC's architecture automatically fully re-finalizes, re-connects, etc. the model on each user-enacted edit (effectively, it calls `finalizeFromProperties`, `finalizeConnections`, `buildSystem`, etc.), so if the inertia tensor isn't being updated on each edit that would indicate that something in the `Body` class retains information that can only be wiped by entirely creating a brand new model from scratch - ouch

Let me investigate this and get back!

**Comment by adamkewley** [comment]
Yes, it's a bug in OpenSim.

- `OpenSim::Body` has both a property for inertia (the thing the user edits) and a `_inertia` member. The simulation part of the codebase uses the `_inertia` member by asking for it via `Body::getInertia`, whereas user-editing code will edit the property
  - The property: https://github.com/opensim-org/opensim-core/blob/4.4/OpenSim/Simulation/SimbodyEngine/Body.h#L55
  - The `_inertia` member: https://github.com/opensim-org/opensim-core/blob/4.4/OpenSim/Simulation/SimbodyEngine/Body.h#L133
- `getInertia` only updates `_inertia` from the property the first time it's called. So if your model contains an inertia property value of (e.g. `V`) it will initially detect that `_inertia` is NaN (its "not set" value) and update it to be `V`, but subsequent calls will detect it is != NaN and skip updating
  - The check: https://github.com/opensim-org/opensim-core/blob/4.4/OpenSim/Simulation/SimbodyEngine/Body.cpp#L129
- `finalizeFromProperties` doesn't reset `_inertia` to the new user-enacted value or, at least, reset it to NaN to re-trigger an update: https://github.com/opensim-org/opensim-core/blob/4.4/OpenSim/Simulation/SimbodyEngine/Body.cpp#L80

So the bug is that some state within OpenSim is updated from the model property (i.e. the thing you edit in the UI, or the osim file, or OpenSim GUI) but a dependent state (here, `_inertia`) isn't updated to reflect the updated value, and the `finalizeFromProperties` call isn't adequately re-flagging that dependent state.

OSC's failing because, after each edit of the model, it's only re-finalizing everything, rather than nuking everything and rebuilding it from scratch (which would potentially be much slower, because that would cause things like mesh files to re-load inside OpenSim).

**Comment by adamkewley** [comment]
@jesse-gilmer , I've what (I believe to be) a fix to the bug in OSC, because it might take a while to propagate the fix through OpenSim's core library codebase (I'll write it up for that repo also, though).

If you could give the fix a try by:

- Waiting for the fix to be built by GitHub here: https://github.com/ComputationalBiomechanicsLab/opensim-creator/actions/runs/4132749362
- Scroll to `Artifacts`
- Download the appropriate artifact for your platform an install it
- Confirm it's behaving the way you think it should

Out of curiosity, how exactly are you gauging inertia changes? I don't personally do much modelling, so I'm unsure how to "eyeball" the bug?

**Comment by adamkewley** [comment]
Ok, so:

- I'm assuming the hotfix is probably going to be alright in OSC (3342e87)
- If it isn't ok, I can have another swing at it (I'd rather move quickly with a fix than dilly-daddle discussing solutions)
- I upstreamed the issue to OpenSim itself (https://github.com/opensim-org/opensim-core/issues/3395), which should bring attention to it and hopefully get it fixed in OpenSim GUI
- And PRed OpenSim core with a one-liner hotfix that will (probably, although hackily) fix the issue for the vast majority of use-cases, incl. OpenSim GUI (https://github.com/opensim-org/opensim-core/pull/3396)

If there's any issues with these  (e.g. I've mischaracterized the issue, that isn't the bug, etc.) I'll take another swing at it - I haven't rebuilt OpenSim, reran all tests, wrote a new test, etc. for this bug because it was easy enough to spot by reading through the C++ (if my guess is correct, that is).

**Comment by adamkewley** [comment]
@jesse-gilmer , if you get a change, give the latest Actions build(s) a whirl (some are red, because Linux builds are stricter, but a green Windows/Mac build in them should be fine)

If there's no problem, I'll likely close this sometime next week, or the week after, during a release QA push (that is, if it works ;)).

**Comment by adamkewley** [comment]
This is now also fixed in `opensim-core`, so OpenSim 4.5 shouldn't observe this behavior anymore, either:

https://github.com/opensim-org/opensim-core/pull/3396
