### ISSUE TITLE
Fix unable to add Ligament and PathSpring due to missing 'Path Points selection' section in creation window

### ISSUE THREAD

**Issue by AdrianHendrik** [ComputationalBiomechanicsLab/opensim-creator#645]
"ligament' and 'PathSpring' elements are unable to be added to a model due to the lack of a 'Path Points selection' section and thus the inability to create a geometrypath. 

Trying to add those elements gives the following error message:
**"Error adding component to model: Property 'PathPointSet' has an invalid value. (details: A valid path must be connected to a model by at least two PathPoints.)."**
However there is no section in the creation screen to select PathPoints.

Other forces that require a geometry path (McKibbenActuators, Millard2012accelerationMuscle, Millard2012EquilibriumMuscle, RigidTendonMuscle) do have such a section at the bottom of the creation window:
![image](https://user-images.githubusercontent.com/62060565/224029387-d8840689-1185-42d9-8d52-823c25a82e6e.png)
'Ligament' and 'PathSpring', however, are missing this section.

**Comment by adamkewley** [comment]
Actually fully fixing this bug such that `GeometryPath`s can be edited via property editors is going to require a fairly large amount of code changes (original estimates from #30 is 2-4d) because the property editors need to be redesigned such that each property editor can potentially spawn sub-popups (e.g. imagine editing a `GeometryPath` within some larger popup) and so that each property editor can querty the target model (e.g. imagine the `GeometryPath` editor wants to ask something like "what stations are currently in the model?").

The previous design assumes each property editor renders in-place and doesn't really need to know anything about the rest of the model, so various internal API's need to be refactored to support passing the necessary stuff around - I might not be able to slip this into the hotfix release, but I will try and push and redesign steps that work toward this fix with these issues tagged.

**Comment by adamkewley** [comment]
This is effectively fixed in 69941be and beyond. You can grab a build that contains the feature in the `Actions` tab after it's built (artifacts section, here: https://github.com/ComputationalBiomechanicsLab/opensim-creator/actions/runs/4417075956)

- The top-level part of this bug--that it's impossible to add a `PathSpring` via the GUI because there's no way to edit the `GeometryPath` is now fixed.
- A further enhancement issue--of being able to also associate wrap objects to a path--was broken out into #646.
- A further minor bug that I found--of not being able to click points within a `PathSpring`--was broken out into #647

@AdrianHendrik , here's a video showing the new functionality. The same functionality also applies to the Property editor panel (i.e. you can use this new popup to edit an existing path within an existing model as well):


https://user-images.githubusercontent.com/4730570/225045120-4de8a979-f113-4a3f-bfa2-3dbf454ecf70.mp4

If there's any bugs in the implementation then I'll break those out as separate issues.
