### ISSUE TITLE
Add real-time visualization of a spring when adding it to the model

### ISSUE THREAD

**Issue by itbellix** [ComputationalBiomechanicsLab/opensim-creator#676]
Hi @adamkewley, first of all apologies if this is a duplicate.
I am trying to add a spring to an OpenSim model using OSC, but I have to repeat the process quite some times as, when the spring properties and attachment points are being chosen, I still don't know how the resulting spring would look like. It would help a lot if the spring was kind of pre-visualized (once `body1` and `body2` are selected), so that the corresponding `point1` and `point2` could be selected precisely and more easily.
This is how the tool looks now:
![image](https://user-images.githubusercontent.com/50029203/233955029-cd2f58ad-07c5-4052-b443-43d3f13bb8fd.png)
and what I mean is that it is difficult to guess the numbers to put in `point1`\\`point2` fields without any visualization.
Thank you very much!

**Comment by adamkewley** [comment]
I cannot add a pre-visualization as you request because visualizing the model strictly requires that the component has been successfully added the model. The panel you are clicking is editing a spring that has not yet been added to the model (and, by default, it will obscure the middle of the screen, so the UX of placing it next to a visualizer would *also* need to be changed to accomodate a flow like that).

You should be able to edit any field on a `PointToPointSpring` once it is added to the model - check the `log` Window in case there is some kind of SimTK-/OpenSim-related reason that's preventing that mutation (it works fine for me).

**Comment by itbellix** [comment]
Hi @adamkewley, thank you for the clarification. Indeed, I managed to edit the `point1` field now (not sure why, I did not find the correct window before), and I guess doing this can also solve my request earlier. I can just add a spring, and then modify its fields seeing the visualization updated in real-time.
Thank you, I will close this!
