### ISSUE TITLE
Change the working directory following deragging a model

### ISSUE THREAD

**Issue by mrrezaie** [ComputationalBiomechanicsLab/opensim-creator#918]
Hi, in OpenSim, I'm used to dragging the model into the workspace, then when I load motion or open any file, the file browser opens in the same directory the model was located. But this is not the case in OSC. I have to change the directory and look for the desired files. It would be great if OSC has this functionality, just for ease of use.

I hope I explained it properly. Thank you in advance.

**Comment by adamkewley** [comment]
I'll try and look into this, but no promises - OSC is currently using the native file dialog API that's offered by each operating system, via `nativefiledialog`, so I have to investigate how to provide hints to the OS without opening the dialog (the OS automatically remembers recent dialog usage but it doesn't "connect the dots" with the fact that drag+dropping a file might also be interpreted as "a file usage", or that having a tab open in the UI could constitute "currently looking at a file, so open the dialog close to that file").

**Comment by adamkewley** [comment]
This is now implemented in the `main` branch @mrrezaie . Assuming no compiler issues (never a guarantee), it'll be available in the Actions tab in 1-2 hours. Otherwise, the next formal release, which will contain this fix, should come out in 1-2 weeks.

Thanks for reporting it! Please post here if it's broken, wrong, etc. - this was a quick job.

**Comment by mrrezaie** [comment]
@adamkewley, thanks a lot for this feature. I just tested the artifact and it worked perfectly. It's now very convenient. Thank for your time and support.
