### ISSUE TITLE
Move "Re-Express in new frame" Checkbox to top of socket-reassignment popup

### ISSUE THREAD

**Issue by tgeijten** [ComputationalBiomechanicsLab/opensim-creator#959]
When changing the frame of a path point, it would be nice if the location would be automatically adapted to the new frame, in such a way that the global position stays the same. At the moment, the offset stays the same, even though this offset usually has no significance in the new reference frame.

This already happens when you select a different expression frame in the path point properties: the location is automatically shown in the new frame (which is really nice). It would be great if this also happens when you actually change the frame.

This is incredibly useful if you want to attach a pathpoint to a different body, without changing its global position (given the current pose).

**Comment by adamkewley** [comment]
This is available as a `Re-Express in new frame` checkbox when reassigning the frame's `Parent` socket via `Sockets > Parent > Edit` or similar. The checkbox should appear whenever OSC detects that the socket is related to frames (e.g. point parent, joint frame parent, etc.) and it'll do the necessary maths to ensure that the ground location of the component doesn't change, but the frame it's attached to should.

Is that sufficient, or is there a different flow you're using to re-frame the point? The wording was a suggestion from a researcher at TUD but could also be changed.

The editor's ability to select a frame is specifically a read/write transform that helps with editing the property, but doesn't change the point's frame (because I figured it would be very annoying to code that in, and it might be not-obvious to a user that some property on a component is related to some other socket-related property, etc.)

**Comment by tgeijten** [comment]
Aha, great, thanks! I didn't notice that checkbox, perhaps because it's beneath the frame list, while the dialog closes as soon as you single-click on any item in the list.

Not sure if it's just me, but I think having an Ok button or putting the checkbox at the top would've guided me in the right direction 😄

**Comment by adamkewley** [comment]
I'll move it up-top for this issue then!

**Comment by adamkewley** [comment]
The socket reassignment popup was given a redesign to make it a bit tidier and to move the `Re-Express` option to a clearer location. The user must now also first select a socket *and then* click `Ok`, which gives a little bit of temporal breathing room ("ok, now I'm going over to the `Ok` button, wait, what's this checkbox..."). Additionally, there's a help marker that explains what the checkbox does, should it be unclear from the wording.

Before:

![image](https://github.com/user-attachments/assets/b16473b2-1ac8-4f08-9250-22dcfe0e3f0b)

After:

![image](https://github.com/user-attachments/assets/52d77097-5ea5-440c-93fd-d0339a80bc0a)

**Comment by tgeijten** [comment]
Thank you, that's a major improvement IMHO!
